class Country {
  final String code;
  final String name;
  final String asset;

  const Country({
    required this.code,
    required this.name,
    required this.asset,
  });
}

const Map<String, String> _countryNames = {
  'ad': 'Andorra',
  'ae': 'United Arab Emirates',
  'af': 'Afghanistan',
  'ag': 'Antigua and Barbuda',
  'al': 'Albania',
  'am': 'Armenia',
  'ao': 'Angola',
  'aq': 'Antarctica',
  'ar': 'Argentina',
  'ara': 'Arabic',
  'as': 'American Samoa',
  'ase': 'American Sign Language',
  'at': 'Austria',
  'au': 'Australia',
  'aw': 'Aruba',
  'ax': 'Åland Islands',
  'az': 'Azerbaijan',
  'ba': 'Bosnia and Herzegovina',
  'bb': 'Barbados',
  'bd': 'Bangladesh',
  'be': 'Belgium',
  'bf': 'Burkina Faso',
  'bg': 'Bulgaria',
  'bh': 'Bahrain',
  'bi': 'Burundi',
  'bj': 'Benin',
  'bl': 'Saint Barthélemy',
  'bm': 'Bermuda',
  'bn': 'Brunei Darussalam',
  'bo': 'Bolivia',
  'bq': 'Bonaire, Sint Eustatius and Saba',
  'br': 'Brazil',
  'bs': 'Bahamas',
  'bt': 'Bhutan',
  'bv': 'Bouvet Island',
  'bw': 'Botswana',
  'by': 'Belarus',
  'bz': 'Belize',
  'ca': 'Canada',
  'cc': 'Cocos (Keeling) Islands',
  'cd': 'Democratic Republic of the Congo',
  'cef': 'Central European Free Trade Agreement',
  'cf': 'Central African Republic',
  'cg': 'Republic of the Congo',
  'ch': 'Switzerland',
  'ci': 'Ivory Coast',
  'ck': 'Cook Islands',
  'cl': 'Chile',
  'cm': 'Cameroon',
  'cn': 'China',
  'co': 'Colombia',
  'cp': 'Clipperton Island',
  'cr': 'Costa Rica',
  'cu': 'Cuba',
  'cv': 'Cabo Verde',
  'cw': 'Curaçao',
  'cx': 'Christmas Island',
  'cy': 'Cyprus',
  'cz': 'Czech Republic',
  'de': 'Germany',
  'dg': 'Diego Garcia',
  'dj': 'Djibouti',
  'dk': 'Danish',
  'dm': 'Dominica',
  'do': 'Dominican Republic',
  'dz': 'Algeria',
  'eac': 'East African Community',
  'ec': 'Ecuador',
  'ee': 'Estonia',
  'eg': 'Egypt',
  'eh': 'Western Sahara',
  'er': 'Eritrea',
  'es-ct': 'Catalan',
  'es-ga': 'Galician',
  'es-pv': 'Basque',
  'es': 'Spanish',
  'et': 'Estonian',
  'eu': 'European Union',
  'fi': 'Finland',
  'fj': 'Fiji',
  'fk': 'Falkland Islands',
  'fm': 'Micronesia',
  'fo': 'Faroe Islands',
  'fr': 'France',
  'ga': 'Gabon',
  'gb-eng': 'England',
  'gb-nir': 'Northern Ireland',
  'gb-sct': 'Scotland',
  'gb-wls': 'Wales',
  'gb': 'United Kingdom',
  'gd': 'Grenada',
  'ge': 'Georgia',
  'gf': 'French Guiana',
  'gg': 'Guernsey',
  'gh': 'Ghana',
  'gi': 'Gibraltar',
  'gl': 'Greenland',
  'gm': 'Gambia',
  'gn': 'Guinea',
  'gp': 'Guadeloupe',
  'gq': 'Equatorial Guinea',
  'gr': 'Greece',
  'gs': 'South Georgia and the South Sandwich Islands',
  'gt': 'Guatemala',
  'gu': 'Guam',
  'gw': 'Guinea-Bissau',
  'gy': 'Guyana',
  'hk': 'Hong Kong',
  'hm': 'Heard Island and McDonald Islands',
  'hn': 'Honduras',
  'hr': 'Croatia',
  'ht': 'Haiti',
  'hu': 'Hungary',
  'ic': 'Canary Islands',
  'id': 'Indonesia',
  'ie': 'Ireland',
  'il': 'israel',
  'im': 'Isle of man',
  'in': 'India',
  'io': 'British Indian Ocean Territory',
  'iq': 'Iraq',
  'ir': 'Iran',
  'is': 'Iceland',
  'it': 'Italy',
  'je': 'Jersey',
  'jm': 'Jamaica',
  'jo': 'Jordan',
  'jp': 'Japan',
  'ke': 'Kenya',
  'kg': 'Kyrgyzstan',
  'kh': 'Cambodia',
  'ki': 'Kiribati',
  'km': 'Comoros',
  'kn': 'Saint Kitts and Nevis',
  'kp': 'North Korea',
  'kr': 'South Korea',
  'kw': 'Kuwait',
  'ky': 'Cayman Islands',
  'kz': 'Kazakhstan',
  'la': 'Laos',
  'lb': 'Lebanon',
  'lc': 'Saint Lucia',
  'li': 'Liechtenstein',
  'lk': 'Sri Lanka',
  'lr': 'Liberia',
  'ls': 'Lesotho',
  'lt': 'Lithuania',
  'lu': 'Luxembourg',
  'lv': 'Latvia',
  'ly': 'Libya',
  'ma': 'Morocco',
  'mc': 'Monaco',
  'md': 'Moldova',
  'me': 'Montenegro',
  'mf': 'Saint Martin',
  'mg': 'Madagascar',
  'mh': 'Marshall Islands',
  'mk': 'North Macedonia',
  'ml': 'Mali',
  'mm': 'Myanmar',
  'mn': 'Mongolia',
  'mo': 'Macao',
  'mp': 'Northern Mariana Islands',
  'mq': 'Martinique',
  'mr': 'Mauritania',
  'ms': 'Montserrat',
  'mt': 'Malta',
  'mu': 'Mauritius',
  'mv': 'Maldives',
  'mw': 'Malawi',
  'mx': 'Mexico',
  'my': 'Malaysia',
  'mz': 'Mozambique',
  'na': 'Namibia',
  'nc': 'New Caledonia',
  'ne': 'Niger',
  'nf': 'Norfolk Island',
  'ng': 'Nigeria',
  'ni': 'Nicaragua',
  'nl': 'Netherlands',
  'no': 'Norway',
  'np': 'Nepal',
  'nr': 'Nauru',
  'nu': 'Niue',
  'nz': 'New Zealand',
  'om': 'Oman',
  'pa': 'Panama',
  'pc': 'Pacific Islands Forum',
  'pe': 'Peru',
  'pf': 'French Polynesia',
  'pg': 'Papua New Guinea',
  'ph': 'Philippines',
  'pk': 'Pakistan',
  'pl': 'Poland',
  'pm': 'Saint Pierre and Miquelon',
  'pn': 'Pitcairn Islands',
  'pr': 'Puerto Rico',
  'ps': 'Palestine',
  'pt': 'Portugal',
  'pw': 'Palau',
  'py': 'Paraguay',
  'qa': 'Qatar',
  're': 'Réunion',
  'ro': 'Romania',
  'rs': 'Serbia',
  'ru': 'Russia',
  'rw': 'Rwanda',
  'sa': 'Saudi Arabia',
  'sb': 'Solomon Islands',
  'sc': 'Seychelles',
  'sd': 'Sudan',
  'se': 'Sweden',
  'sg': 'Singapore',
  'sh-ac': 'Ascension Island',
  'sh-hl': 'Saint Helena',
  'sh-ta': 'Tristan da Cunha',
  'sh': 'Saint Helena, Ascension and Tristan da Cunha',
  'si': 'Slovenia',
  'sj': 'Svalbard and Jan Mayen',
  'sk': 'Slovakia',
  'sl': 'Sierra Leone',
  'sm': 'San Marino',
  'sn': 'Senegal',
  'so': 'Somalia',
  'sr': 'Suriname',
  'ss': 'South Sudan',
  'st': 'São Tomé and Príncipe',
  'sv': 'El Salvador',
  'sx': 'Sint Maarten',
  'sy': 'Syria',
  'sz': 'Eswatini',
  'tc': 'Turks and Caicos Islands',
  'td': 'Chad',
  'tf': 'French Southern Territories',
  'tg': 'Togo',
  'th': 'Thailand',
  'tj': 'Tajikistan',
  'tk': 'Tokelau',
  'tl': 'Timor-Leste',
  'tm': 'Turkmenistan',
  'tn': 'Tunisia',
  'to': 'Tonga',
  'tr': 'Turkey',
  'tt': 'Trinidad and Tobago',
  'tv': 'Tuvalu',
  'tw': 'Taiwan',
  'tz': 'Tanzania',
  'ua': 'Ukraine',
  'ug': 'Uganda',
  'um': 'United States Minor Outlying Islands',
  'un': 'United Nations',
  'us': 'United States',
  'uy': 'Uruguay',
  'uz': 'Uzbekistan',
  'va': 'Vatican City',
  'vc': 'Saint Vincent and the Grenadines',
  've': 'Venezuela',
  'vg': 'British Virgin Islands',
  'vi': 'United States Virgin Islands',
  'vn': 'Vietnam',
  'vu': 'Vanuatu',
  'wf': 'Wallis and Futuna',
  'ws': 'Samoa',
  'xk': 'Kosovo',
  'xx': 'Unknown',
  'ye': 'Yemen',
  'yt': 'Mayotte',
  'za': 'South Africa',
  'zm': 'Zambia',
  'zw': 'Zimbabwe',
};

List<Country> get supportedCountries {
  const codes = [
    'ad',
    'ae',
    'af',
    'ag',
    'al',
    'am',
    'ao',
    'aq',
    'ar',
    'arab',
    'as',
    'asean',
    'at',
    'au',
    'aw',
    'ax',
    'az',
    'ba',
    'bb',
    'bd',
    'be',
    'bf',
    'bg',
    'bh',
    'bi',
    'bj',
    'bl',
    'bm',
    'bn',
    'bo',
    'bq',
    'br',
    'bs',
    'bt',
    'bv',
    'bw',
    'by',
    'bz',
    'ca',
    'cc',
    'cd',
    'cefta',
    'cf',
    'cg',
    'ch',
    'ci',
    'ck',
    'cl',
    'cm',
    'cn',
    'co',
    'cp',
    'cr',
    'cu',
    'cv',
    'cw',
    'cx',
    'cy',
    'cz',
    'de',
    'dg',
    'dj',
    'dk',
    'dm',
    'do',
    'dz',
    'eac',
    'ec',
    'ee',
    'eg',
    'eh',
    'er',
    'es-ct',
    'es-ga',
    'es-pv',
    'es',
    'et',
    'eu',
    'fi',
    'fj',
    'fk',
    'fm',
    'fo',
    'fr',
    'ga',
    'gb-eng',
    'gb-nir',
    'gb-sct',
    'gb-wls',
    'gb',
    'gd',
    'ge',
    'gf',
    'gg',
    'gh',
    'gi',
    'gl',
    'gm',
    'gn',
    'gp',
    'gq',
    'gr',
    'gs',
    'gt',
    'gu',
    'gw',
    'gy',
    'hk',
    'hm',
    'hn',
    'hr',
    'ht',
    'hu',
    'ic',
    'id',
    'ie',
    'il',
    'im',
    'in',
    'io',
    'iq',
    'ir',
    'is',
    'it',
    'je',
    'jm',
    'jo',
    'jp',
    'ke',
    'kg',
    'kh',
    'ki',
    'km',
    'kn',
    'kp',
    'kr',
    'kw',
    'ky',
    'kz',
    'la',
    'lb',
    'lc',
    'li',
    'lk',
    'lr',
    'ls',
    'lt',
    'lu',
    'lv',
    'ly',
    'ma',
    'mc',
    'md',
    'me',
    'mf',
    'mg',
    'mh',
    'mk',
    'ml',
    'mm',
    'mn',
    'mo',
    'mp',
    'mq',
    'mr',
    'ms',
    'mt',
    'mu',
    'mv',
    'mw',
    'mx',
    'my',
    'mz',
    'na',
    'nc',
    'ne',
    'nf',
    'ng',
    'ni',
    'nl',
    'no',
    'np',
    'nr',
    'nu',
    'nz',
    'om',
    'pa',
    'pc',
    'pe',
    'pf',
    'pg',
    'ph',
    'pk',
    'pl',
    'pm',
    'pn',
    'pr',
    'ps',
    'pt',
    'pw',
    'py',
    'qa',
    're',
    'ro',
    'rs',
    'ru',
    'rw',
    'sa',
    'sb',
    'sc',
    'sd',
    'se',
    'sg',
    'sh-ac',
    'sh-hl',
    'sh-ta',
    'sh',
    'si',
    'sj',
    'sk',
    'sl',
    'sm',
    'sn',
    'so',
    'sr',
    'ss',
    'st',
    'sv',
    'sx',
    'sy',
    'sz',
    'tc',
    'td',
    'tf',
    'tg',
    'th',
    'tj',
    'tk',
    'tl',
    'tm',
    'tn',
    'to',
    'tr',
    'tt',
    'tv',
    'tw',
    'tz',
    'ua',
    'ug',
    'um',
    'un',
    'us',
    'uy',
    'uz',
    'va',
    'vc',
    've',
    'vg',
    'vi',
    'vn',
    'vu',
    'wf',
    'ws',
    'xk',
    'xx',
    'ye',
    'yt',
    'za',
    'zm',
    'zw',
  ];

  return codes.map((code) {
    final name = _countryNames[code] ?? code.toUpperCase();
    return Country(
      code: code,
      name: name,
      asset: 'assets/flags/$code.svg',
    );
  }).toList();
}
